### PR TITLE
Bump nalgebra version in response to RUSTSEC-2021-0070

### PR DESCRIPTION
**Pull request by sage-tpfs**
Advisory page with more context: https://rustsec.org/advisories/RUSTSEC-2021-0070

I verified the test suite passes, but otherwise didn't do any additional verification.

### CODE REVIEW

**Comment by n1m3** [comment]
Looks good to me.
I should really get into the habit of running cargo audit regularly.
Thanks a lot!

**Comment by n1m3** [comment]
Okay, a new version is up on [crates.io](https://crates.io/crates/linregress), however the newest [statrs](https://crates.io/crates/statrs/0.14.0) version still depends on nalgebra 0.26.
I'll do another version bump, once they update.

**Comment by sage-tpfs** [comment]
Thank you, @n1m3! That's a good point about `statrs` that I hadn't considered yet.

> I should really get into the habit of running cargo audit regularly.

Have you considered enabling [Dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/)? It helps a lot.

**Comment by n1m3** [comment]
Hey @sage-tpfs,
`statrs` has now published a new version, where they also bumped `nalgebra`.
So now `0.27.1` is the only version of `nalgebra` that `linregress` depends on.
I've published [version 0.4.3](https://crates.io/crates/linregress/0.4.3) with this change.

I've also gone ahead and enabled Dependabot for security issues.
Thanks again!

**Pull request merged**
