### PR TITLE
Add prediction feature for model

### PR DESCRIPTION
**Pull request by jonahweissman**
I'm not sure if this is out of scope for your project, but, for one of my projects, I wanted the ability to use a model to get predictions on unseen data. This PR adds that capability.

Other than adding the `predict` function itself, I made a small change to the `pairs` method, that stops it from consuming the `RegressionModel` when called.

### CODE REVIEW

**Comment by n1m3** [comment]
Predicting on unseen data didn't come up in the original use case I wrote this library for, so I didn't even consider including it.
I would say that it is definitely in scope for a linear regression library though.
Thank you for implementing it!

The change to pairs makes sense to me with the added functionality; we can probably have it return &str instead of cloning the Strings.
I think I may be able to eliminate some of the cloning in the predict and check_variables functions as well, but I'll just merge this as is for now.
Thanks again!

**Comment by jonahweissman** [comment]
Excellent, thank you for accepting my contributions!

I'm still pretty new at Rust, so all the cloning was just me getting frustrated with the borrow checker. I'm sure there's a better way to do it.

I should have mentioned this a little earlier, but do you have any thoughts on `predict` accepting a vector of points (as it's currently written) versus just a single point? I chose a vector of points just because it seemed more flexible (and because [scikit-learn's LinearRegression implementation does it that way](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html#sklearn.linear_model.LinearRegression.predict)), but I wanted to make sure you had considered both alternatives.

**Comment by n1m3** [comment]
I think taking multiple points at once is the way to go, as the checking and setup with all the HashMaps/Sets is pretty expensive.
So calling `predict` in a loop will probably be a lot slower than just calling it once with all points.
Statsmodels has the same approach as well.

**Comment by n1m3** [comment]
I have [refactored](https://github.com/n1m3/linregress/blob/master/src/lib.rs#L600) `predict` to use nalgebra for the calculations, changed the verification / error handling to cover more cases and added custom `ErrorKinds` for errors in `predict`.
Let me know if it still behaves as you would expected for your use case.

Unless you can thing of something that needs to be changed (e.g. a failure case I didn't consider), I'll push out a new release.

**Comment by jonahweissman** [comment]
This looks fantastic! It still behaves as I expect.

This is probably a breaking change (and somewhat unrelated to `predict`), but you can implement methods on an `enum`. Since the `Error` struct only contains an `ErrorKind`, you could simplify it a bit by implementing `std::Error` directly on `ErrorKind`. Obviously, it works fine the way it is now, but this would remove the need to call `Error::new`.

**Comment by n1m3** [comment]
That's an excellent idea! I think when I switched to using my own error type, I implemented it based on an example (probably ripgrep) that was using an "old" way to implement Error. `display` is deprecated as well.
So since this is a breaking change anyways (because `pairs` return type changed), I may as well fix this now.

**Comment by jonahweissman** [comment]
Perfect! I forgot that `pairs` had changed.

While you're at it, `cargo clippy` has a few minor suggestions, mostly readability-related.

**Comment by n1m3** [comment]
Alright, done. I didn't realize enums could be marked as non_exhaustive now (apparently since Rust 1.40).
That's pretty neat.

Anything else?

**Comment by jonahweissman** [comment]
Looks good to me! Thanks so much for all your work on this

**Comment by n1m3** [comment]
New version is published. Thanks again for your contribution!

**Pull request merged**
